INSERT INTO `books`(`booksId`, `booksImg`,  `booksName`) VALUE 
(23, '23.jpg', 'Программирование на языке Go!'),
(25, '25.jpg', 'Толковый словарь сетевых терминов и аббревиатур'),
(26, '26.jpg', 'Python for Data Analysis'),
(27, '27.jpg', 'Thinking in Java (4th Edition)'),
(29, '29.jpg', 'Introduction to Algorithms'),
(31, '31.jpg', 'JavaScript Pocket Reference'),
(32, '32.jpg', 'Adaptive Code via C#: Class and Interface Design, Design Patterns, and SOLID Principles'),
(33, '33.jpg', 'SQL: The Complete Referenc'),
(34, '34.jpg', 'PHP and MySQL Web Development'),
(35, '35.jpg', 'Статистический анализ и визуализация данных с помощью R'),
(36, '36.jpg', 'Computer Coding for Kid'),
(37, '37.jpg', 'Exploring Arduino: Tools and Techniques for Engineering Wizardry'),
(38, '38.jpg', 'Программирование микроконтроллеров для начинающих и не только'),
(39, '39.jpg', 'The Internet of Things'),
(40, '40.jpg', 'Sketching User Experiences: The Workbook'),
(41, '41.jpg', 'InDesign CS6'),
(42, '42.jpg', 'Адаптивный дизайн. Делаем сайты для любых устройств'),
(43, '43.jpg', 'Android для разработчиков'),
(44, '44.jpg', 'Clean Code: A Handbook of Agile Software Craftsmanship'),
(45, '45.jpg', 'Swift Pocket Reference: Programming for iOS and OS X'),
(46, '46.jpg', 'NoSQL Distilled: A Brief Guide to the Emerging World of Polyglot Persistence'),
(47, '47.jpg', 'Head First Ruby'),
(48, '48.jpg', 'Practical Vim');